name: preview

on:
  pull_request:
    types:
      - labeled

jobs:
  release:
    name: Preview release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - id: bumpr
        if: "!startsWith(github.ref, 'refs/tags/')"
        name: Bump versions
        uses: haya14busa/action-bumpr@v1